[project]
name = "ajpp-modena"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
	"beautifulsoup4>=4.13.0",
	"requests>=2.32.0",
	"streamlit>=1.41.0",
]
